import { Person } from "@/app/people/page";

export const data: Person[] = [
  {
    id: 1,
    name: "Smith",
    age: 25,
    bio: "Aspiring developer",
    gender: "male",
  },
  {
    id: 2,
    name: "Mary",
    age: 28,
    bio: "Loves photography",
    gender: "female",
  },
  { id: 3, name: "Joe", age: 27, bio: "Basketball fan", gender: "male" },
  { id: 4, name: "Anna", age: 22, bio: "Graduate student", gender: "female" },
  { id: 5, name: "David", age: 30, bio: "Software engineer", gender: "male" },
  { id: 6, name: "Elena", age: 25, bio: "Digital artist", gender: "female" },
  { id: 7, name: "Chris", age: 19, bio: "Skateboarder", gender: "male" },
  {
    id: 8,
    name: "Sophie",
    age: 21,
    bio: "Coffee enthusiast",
    gender: "female",
  },
  { id: 9, name: "Liam", age: 28, bio: "Travel blogger", gender: "male" },
  { id: 10, name: "Olivia", age: 24, bio: "UI designer", gender: "female" },
  { id: 11, name: "Noah", age: 26, bio: "Web developer", gender: "male" },
  { id: 12, name: "Emma", age: 27, bio: "Yoga instructor", gender: "female" },
  { id: 13, name: "Ethan", age: 32, bio: "Chef", gender: "male" },
  { id: 14, name: "Mia", age: 23, bio: "Musician", gender: "female" },
  { id: 15, name: "Lucas", age: 29, bio: "Data scientist", gender: "male" },
  {
    id: 16,
    name: "Isabella",
    age: 20,
    bio: "History buff",
    gender: "female",
  },
  { id: 17, name: "Mason", age: 26, bio: "Architect", gender: "male" },
  { id: 18, name: "Ava", age: 31, bio: "Writer", gender: "female" },
  { id: 19, name: "James", age: 35, bio: "Product manager", gender: "male" },
  { id: 20, name: "Charlotte", age: 22, bio: "Gardener", gender: "female" },
];
